FROM endial/alpine:v3.11

LABEL \
	"Version"="0.0.0" \
	"Description"="Description info for current image." \
	"Dockerfile"="https://github.com/cofigo/docker-libs" \
	"Vendor"="Endial Fang (endial@126.com)"


CMD []
